### ISSUE TITLE
Can't upgrade/clean install Hosts Blocker 

### ISSUE THREAD

**Issue by aav7fl** [arcetera/arcetera.github.io#3]
hi there. This morning you updated the minimal hosts blocker. I am now unable to update or cleanly install the minimal hosts blocker. Here the two screenshots below from an attempted upgrade and from an attempted clean install. The upgrade is on a device that already had it, and the clean install is on a new device.

![2015-05-23 08 54 53 png](https://cloud.githubusercontent.com/assets/3487107/7784158/c43ef852-0129-11e5-942b-bbeea83d1529.jpg)
![2015-05-23 08 54 56](https://cloud.githubusercontent.com/assets/3487107/7784159/c43f67d8-0129-11e5-869b-04898000ba3d.png)

**Comment by arcetera** [comment]
Should be fixed now, sorry for the inconvenience

**Comment by aav7fl** [comment]
It's no problem. It's working perfectly now. Thanks for the quick response!
